// Embed codes copied directly from TikTok share → Embed for each video
// Stored in a separate file to avoid JSX parser issues with unicode characters

export const TIKTOK_EMBEDS = [
  `<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@itsmcmartyfly/video/7578691659601431822" data-video-id="7578691659601431822" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@itsmcmartyfly" href="https://www.tiktok.com/@itsmcmartyfly?refer=embed">@itsmcmartyfly</a> Lavender Marriage Questions from the interwebs PT.1 <a title="lavendermarriage" target="_blank" href="https://www.tiktok.com/tag/lavendermarriage?refer=embed">#lavendermarriage</a> <a title="relationships" target="_blank" href="https://www.tiktok.com/tag/relationships?refer=embed">#relationships</a> <a title="couplegoals" target="_blank" href="https://www.tiktok.com/tag/couplegoals?refer=embed">#couplegoals</a> <a title="husbandwife" target="_blank" href="https://www.tiktok.com/tag/husbandwife?refer=embed">#husbandwife</a> <a title="couple" target="_blank" href="https://www.tiktok.com/tag/couple?refer=embed">#couple</a> <a target="_blank" title="♬ Counting my blessings Favour Ojo version - thefavourojo" href="https://www.tiktok.com/music/Counting-my-blessings-Favour-Ojo-version-7467537327260470021?refer=embed">♬ Counting my blessings Favour Ojo version - thefavourojo</a> </section> </blockquote>`,

  `<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@itsmcmartyfly/video/7563048152257858871" data-video-id="7563048152257858871" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@itsmcmartyfly" href="https://www.tiktok.com/@itsmcmartyfly?refer=embed">@itsmcmartyfly</a> <a title="lavendermarriage" target="_blank" href="https://www.tiktok.com/tag/lavendermarriage?refer=embed">#lavendermarriage</a> <a title="intimacy" target="_blank" href="https://www.tiktok.com/tag/intimacy?refer=embed">#intimacy</a> <a title="husbandwife" target="_blank" href="https://www.tiktok.com/tag/husbandwife?refer=embed">#husbandwife</a> <a title="relationships" target="_blank" href="https://www.tiktok.com/tag/relationships?refer=embed">#relationships</a> <a title="couplegoals" target="_blank" href="https://www.tiktok.com/tag/couplegoals?refer=embed">#couplegoals</a> <a target="_blank" title="♬ original sound - \u{1D4C7}\u{1D4EE}\u{1D4EA}\u{1D4F2}\u{1D4FC}\u{1D4FC}\u{1D4F8}\u{1D4FE}\u{1D4F7}\u{1D4B9}\u{1D4EF} \uD83C\uDFA7" href="https://www.tiktok.com/music/original-sound-7416858572367186721?refer=embed">♬ original sound</a> </section> </blockquote>`,

  `<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@itsmcmartyfly/video/7563662830604487991" data-video-id="7563662830604487991" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@itsmcmartyfly" href="https://www.tiktok.com/@itsmcmartyfly?refer=embed">@itsmcmartyfly</a> <a title="lavendermarriage" target="_blank" href="https://www.tiktok.com/tag/lavendermarriage?refer=embed">#lavendermarriage</a> <a title="relationships" target="_blank" href="https://www.tiktok.com/tag/relationships?refer=embed">#relationships</a> <a title="gay" target="_blank" href="https://www.tiktok.com/tag/gay?refer=embed">#gay</a> <a title="couplegoals" target="_blank" href="https://www.tiktok.com/tag/couplegoals?refer=embed">#couplegoals</a> <a title="husbandwife" target="_blank" href="https://www.tiktok.com/tag/husbandwife?refer=embed">#husbandwife</a> <a target="_blank" title="♬ original sound" href="https://www.tiktok.com/music/original-sound-7416858572367186721?refer=embed">♬ original sound</a> </section> </blockquote>`,

  `<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@itsmcmartyfly/video/7582358376353402126" data-video-id="7582358376353402126" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@itsmcmartyfly" href="https://www.tiktok.com/@itsmcmartyfly?refer=embed">@itsmcmartyfly</a> Lavender Marriage 5 words that changed it all! This is part ONE of TEN! come for me all you want just know you only watched the preview!! <a title="lavendermarriage" target="_blank" href="https://www.tiktok.com/tag/lavendermarriage?refer=embed">#lavendermarriage</a> <a title="comingout" target="_blank" href="https://www.tiktok.com/tag/comingout?refer=embed">#comingout</a> <a title="gay" target="_blank" href="https://www.tiktok.com/tag/gay?refer=embed">#gay</a> <a title="modernmarriage" target="_blank" href="https://www.tiktok.com/tag/modernmarriage?refer=embed">#modernmarriage</a> <a title="couple" target="_blank" href="https://www.tiktok.com/tag/couple?refer=embed">#couple</a> <a target="_blank" title="♬ BIRDS OF A FEATHER OFFICIAL INSTRUMENTAL - Dan Swift Del Rey" href="https://www.tiktok.com/music/BIRDS-OF-A-FEATHER-OFFICIAL-INSTRUMENTAL-7442030731718855479?refer=embed">♬ BIRDS OF A FEATHER OFFICIAL INSTRUMENTAL - Dan Swift Del Rey</a> </section> </blockquote>`,
];
